# Generated by Django 5.2.7 on 2026-02-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_complaint_tbll_user_complaint_tbll_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='work_status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
