# Generated by Django 5.2.7 on 2026-02-03 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_book_work_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('message', models.CharField(max_length=50)),
                ('FROM_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FROM_ID', to=settings.AUTH_USER_MODEL)),
                ('TO_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TO_ID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
