# Generated by Django 5.2.7 on 2026-02-05 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_Tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(max_length=50)),
                ('BOOK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.book')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_tbl')),
            ],
        ),
    ]
